apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: superset
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: superset-config
    files:
      - values.yaml=config.yaml
generatorOptions:
  disableNameSuffixHash: true