apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: superset-kustomization
  namespace: flux-system
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: superset-config
    files:
      - values.yaml=config.yaml
generatorOptions:
  disableNameSuffixHash: true