apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset-release
  namespace: flux-system
spec:
  targetNamespace: superset-ns
  releaseName: superset
  chart:
    spec:
      chart: superset
      version: 0.8.7
      sourceRef:
        kind: HelmRepository
        name: superset-repository
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: superset-config
      