apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
  namespace: superset
spec:
  targetNamespace: superset
  releaseName: superset
  chart:
    spec:
      chart: superset
      version: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: superset
  interval: 1m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: superset-config
      