apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: superset
  namespace: superset
spec:
  releaseName: superset
  chart:
    spec:
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system
      version: "0.8.7"
  interval: 5m
  valuesFiles:
    - ./values.yaml